### ISSUE TITLE
DraculaLaf not found 1.12

### ISSUE THREAD

**Issue by KotzaBoss** [Milchreis/UiBooster#40]
So i cloned the repo and added a `Main` class to test some of the new functionalities of version 1.12 but i get this error.
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/bulenkov/darcula/DarculaLaf
	at de.milchreis.uibooster.Main.main(Main.java:9)
Caused by: java.lang.ClassNotFoundException: com.bulenkov.darcula.DarculaLaf
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
```

I tried adding
```
<repository>
            <id>maven.com</id>
            <url>https://mvnrepository.com</url>
</repository>
```
to the pom.xml but no luck.

**Comment by Milchreis** [comment]
hi @KotzaBoss 

the current pom.xml contains a repository for DarcularLaf already:
https://github.com/Milchreis/UiBooster/blob/master/pom.xml#L40

Do you use IntelliJ? Take a right click to pom.xml -> Maven -> Reload project

**Comment by KotzaBoss** [comment]
I recloned it and now its ok... Dont know what i did wrong. Still all is good!

Is the dependency going to be updated to 1.12?

**Comment by Milchreis** [comment]
What do you mean with 
> Is the dependency going to be updated to 1.12?

The DarcularLaf from com.github.ice1k.darcula over JitPack is a part of UiBooster since 1.9.1 and dacular has not changed.

**Comment by KotzaBoss** [comment]
Yeah i worded it horribly.
I meant when will UiBooster 1.12 be available through gradle.
Or perhaps i have also missed that too...

**Comment by Milchreis** [comment]
The release is out now 😄 
[UiBooster 1.12.0](https://github.com/Milchreis/UiBooster/releases/tag/1.12.0)
